### ISSUE TITLE
Error when exporting the archive

### ISSUE THREAD

**Issue by NicolasLourenco** [Hearst-DD/ObjectMapper#796] opened 2017-04-14 13:19 UTC
Hi,
When I try to export my archive. I got this error:
`2017-04-14 13:08:16 +0000 [MT] Presenting: Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in ObjectMapper.framework/ObjectMapper:
error: Cannot extract bundle from /var/folders/3s/qyh334d51dbb_1s4vd_74_hr0000gn/T/XcodeDistPipeline.wjM/Root/Payload/App-iOS.app/Fr…" UserInfo={NSLocalizedDescription=Failed to verify bitcode in ObjectMapper.framework/ObjectMapper:
error: Cannot extract bundle from /var/folders/3s/qyh334d51dbb_1s4vd_74_hr0000gn/T/XcodeDistPipeline.wjM/Root/Payload/App-iOS.app/Fr…}
`

Versions: 
- Carthage 0.20.1
- OjectMapper 2.2.5

Any ideas?

**Comment by tristanhimmelman** [comment] 2017-05-26 18:54
Unfortunately I'm not sure what the issue is here. Closing this for now. If you still haven't resolved, feel free comment and I will reopen.

**Closed by tristanhimmelman** 2017-05-26 18:54 UTC
