### ISSUE TITLE
Swift Array with protocol types fails to convert

### ISSUE THREAD

**Issue by himadrisj** [Hearst-DD/ObjectMapper#536] opened 2016-08-04 11:47 UTC
Please consider code segment:

```
enum SourceType: String {
    case wallet = "WALLET"
    case account = "ACCOUNT"
}

protocol Source: Mappable {
    var type: SourceType { get set }
    var amount: Int { get set }
}

struct WalletSource: Source {
    var userId: String = ""
    var walletId: String = ""
    var type: SourceType = .wallet
    var amount: Int = 0
    
    init(userId: String, walletId: String, amount: Int) {
        self.userId = userId
        self.walletId = walletId
        self.type = .wallet
        self.amount = amount
    }
    
    init?(_ map: Map) { }
    
    mutating func mapping(map: Map) {
        userId <- map["userId"]
        walletId <- map["walletId"]
        type <- map["type"]
        amount <- map["amount"]
    }
}

struct PaymentRequest {
    var sources:[Source] = []
}

extension PaymentRequest: Mappable {
    init?(_ map: Map) { }
    
    mutating func mapping(map: Map) {
        sources <- map["sources"]
    }
}

```

Now conversion of `PaymentRequest` to JSON fails if I try like this:

```
let walletSource = WalletSource(userId: "U12345", walletId: "W6789", amount: 64)
let paymentRequest = PaymentRequest(sources: [walletSource])
let json = Mapper().toJSONString(paymentRequest)
print("JSON string=\(json)")
```

On debugging I was able to figure out that ToJSON::basicType method is not able to convert  Array<Source> to AnyObject.

Is there any way to support this?

I am attaching the sample project.
[TestApp.zip](https://github.com/Hearst-DD/ObjectMapper/files/401528/TestApp.zip)

**Comment by tristanhimmelman** [comment] 2016-08-06 14:59
Closing this as it is a duplicate of #501

**Closed by tristanhimmelman** 2016-08-06 14:59 UTC
