### ISSUE TITLE
Type 'Product' does not conform to protocol 'Mappable'

### ISSUE THREAD

**Issue by abstnc** [Hearst-DD/ObjectMapper#420] opened 2016-03-22 19:53 UTC
Hey I'm having issues with ObjectMapper 1.1.5. I can't set my class to conform to the Mappable protocol. 

`
import Foundation
import ObjectMapper

class Product:Mappable {
    
    var id: Int = 0
    var title: String = ""
    var description: String = ""
    var category: String = ""
    var brand: String = ""
    var priceActual: Float = 0
    var price: Float = 0
    var shipmentIncluded:Bool = false
    var seller: User?
    var images:[Image]?
    var tags:[Tag]?
    var likeCount:Int = 0
    var commentCount:Int = 0
    var isLiked:Bool = false
    var isSold:Bool = false
    var sellerProducts:[Product]?
    var otherProducts:[Product]?
    
    init(){
        
    }

    required init?(_ map: Map) {
        
    }

    func mapping(map: Map){
        
        id                  <- map["id"]
        title               <- map["title"]
        description         <- map["description"]
        category            <- map["category"]
        brand               <- map["brand"]
        priceActual         <- map["priceActual"]
        price               <- map["price"]
        shipmentIncluded    <- map["shipmentIncluded"]
        seller              <- map["seller"]
        images              <- map["images"]
        tags                <- map["tags"]
        likeCount           <- map["likeCount"]
        commentCount        <- map["commentCount"]
        isLiked             <- map["isLiked"]
        sellerProducts      <- map["sellerProducts"]
        otherProducts       <- map["otherProducts"]
    
    }
    
    
}

`

![screen shot 2016-03-22 at 21 51 26](https://cloud.githubusercontent.com/assets/2391962/13965755/4362b194-f078-11e5-98eb-0304836f0858.png)

**Comment by tristanhimmelman** [comment] 2016-03-22 21:16
You're `Product` class looks good to me. Is there is a name space issue and the wrong Product class is being referred to in the API snippet ??

Are you able to write `Mapper<Product>().map(JSON)` within your Product class? If so, that would indicate that something else is causing the issue where it is being used above...

**Comment by abstnc** [comment] 2016-03-23 10:27
No other product class or namespace in my project folders. I cant set any Mappable class.

Like this,

`import Foundation
import ObjectMapper

class Tag:Mappable {
    
    var id:Int = 0
    var name:String = ""
    var url:String = ""
    
    init(){
        
    }
    
    required init?(_ map: Map) {
        
    }
    
    func mapping(map: Map){
        id                  <- map["id"]
        name                <- map["name"]
        url                 <- map["url"]
    }
    
}`

**Comment by tristanhimmelman** [comment] 2016-03-23 15:56
I just tested out the Tag model you pasted out above and it compiles fine in my project. Perhaps the issue is with how you integrated ObjectMapper. Are you using Cocoapods or Carthage?

**Comment by abstnc** [comment] 2016-03-23 16:34
I do not use Cocoapods or Carthage. 
I manually added to the project objectmapper-1.1.5.

**Comment by tristanhimmelman** [comment] 2016-04-05 14:11
Closing this as I believe it is a project set up issue.

**Closed by tristanhimmelman** 2016-04-05 14:11 UTC
