### ISSUE TITLE
nil for Boolean values (true/false)

### ISSUE THREAD

**Issue by dskibin** [Hearst-DD/ObjectMapper#815] opened 2017-05-23 13:55 UTC
Hello, i have issue related to mapping Bool values
After mapping i have nil for CanWrite propery in my mappable object
### Your JSON dictionary:

```json
[
{"guid":"59bab37e-187f-4a75-8137-d1bc1cd8c8d9","beginTime":"08:00","endTime":"08:20","canWrite":false,"busyType":{"name":"some text","type":1}},
{"guid":"0be69b97-cc80-4ab9-8153-a4ce9ac584c6","beginTime":"08:20","endTime":"08:40","canWrite":true,"busyType":{"name":"some text","type":1}}
...]
```

### Your model:

```swift
class ScheduleSlotItem: Mappable {
    var Id: String?
    var BeginTime: String?
    var EndTime: String?
    var CanWrite: Bool?
    var BusyType: ScheduleBusyType?
    
    required init?(map: Map){

    }
    
    init?(){
        
    }
    
    func mapping(map: Map) {
        Id <- map["guid"]
        BeginTime <- map["beginTime"]
        EndTime <- map["endTime"]
        CanWrite <- map["сanWrite"]
        BusyType <- map["busyType"]
    }
}
```

### What you did:

```swift
func GetTimeSchedule(_ lpuId: String, _ doctorId: String, _ dateStr: String) -> Promise<[ScheduleSlotItem]?> {
        KRProgressHUD.show(progressHUDStyle: .whiteColor, message: "Processing data...")
        return Promise {fulfill, reject in
            Alamofire.request(Endpoints.Apis.GetTimeScheduleUrl(lpuId, doctorId, dateStr), encoding: JSONEncoding.default).validate().responseArray{(response: DataResponse<[ScheduleSlotItem]>) in
                switch response.result {
                case .success:
                    if let value = response.result.value {
                        fulfill(value)
                    }
                    KRProgressHUD.dismiss()
                case .failure(let error):
                    KRProgressHUD.dismiss()
                    print(error)
                    
                    let e = NSError(domain: "2dr", code: 0, userInfo: [NSLocalizedDescriptionKey: "Unknown error"])
                    return reject(e)
                }
            }
        }
    }

```

### What you expected:

I exepected property CanWrite filled by values according json
Here is code that allows me to get data from this field if i using responseJSON instead of responseArray

### What you got:
CanWrite is nil

**Comment by tristanhimmelman** [comment] 2017-05-26 19:02
Are you saying that the bool is correctly mapped when using `responseJSON` but not `responseArray`?

Models are mapped the same way using both the methods so I'm not sure what your problem is. You can try appending the following so you can view the output that is not mapping correctly.
```
.responseString(completionHandler: { (response: DataResponse<String>) in
    print(response.value ?? "")
});
```

**Comment by dskibin** [comment] 2017-05-26 19:36
Hello! Thank you for replay!
On the fisrt screenshot you can see json i getting
<img width="1099" alt="screen shot 2017-05-26 at 22 29 28" src="https://cloud.githubusercontent.com/assets/2069948/26509841/4a479220-4263-11e7-99db-3bd60145dcd9.png">

On second -- current implementation, so only responseJson and accessing NSDictionary allows me to get CanWrite value
<img width="1024" alt="screen shot 2017-05-26 at 22 30 18" src="https://cloud.githubusercontent.com/assets/2069948/26509848/53d9312c-4263-11e7-964e-c8ce9dbb2572.png">

Here you can see responseArray usage and CanWrite as nil in watch
<img width="1095" alt="screen shot 2017-05-26 at 22 32 27" src="https://cloud.githubusercontent.com/assets/2069948/26509854/58ce8db2-4263-11e7-8971-eaa10cd3e646.png">

**Comment by henrik-d** [comment] 2017-05-27 13:49
I have the same problem.

**Comment by tristanhimmelman** [comment] 2017-06-30 15:28
Sorry I cannot help anymore but I cannot reproduce this issue. The code looks right to me looking at your screenshots.

Closing this for now. Please feel free to post if you have more issues.

**Closed by tristanhimmelman** 2017-06-30 15:28 UTC

**Comment by omarmasriRO** [comment] 2017-10-31 15:17
I have the same issue !
