### ISSUE TITLE
Hi there are some Error in Xcode Version 10.0 beta (10L176w) & Swift 4.x

### ISSUE THREAD

**Issue by iusn** [Hearst-DD/ObjectMapper#977] opened 2018-06-05 13:29 UTC
like this
![screen shot 2018-06-05 at 9 26 57 pm](https://user-images.githubusercontent.com/11364258/40979120-72eb12da-6907-11e8-8af9-c3993dc8acba.png)

**Comment by asowers1** [comment] 2018-06-05 13:33
seeing the same here

**Comment by arnopoulos** [comment] 2018-06-05 17:14
I believe that this a duplicate of #975

**Comment by Vadimkomis** [comment] 2018-06-06 03:43
seeing the same issue

**Comment by alecdoconnor** [comment] 2018-06-06 12:41
I have created a PR at https://github.com/Hearst-DD/ObjectMapper/pull/978 to hopefully fix this issue. I noticed, after creating it, that another PR exists which has failed tests. Hopefully this produces the right results!

**Comment by joshwoods** [comment] 2018-06-10 22:51
Is there any timeline to be getting a fix in for this? I would like to be moving forward using Xcode 10 to prep for iOS 12, however, this is making it so I cannot even compile our main app. Thanks in advance!

**Comment by alecdoconnor** [comment] 2018-06-10 22:56
Hi Josh! Feel free to contribute to the PR to help us get closer to a working build. I believe this PR technically works, so you would be able to check the branch out directly into your project.

**Comment by madaoCN** [comment] 2018-06-13 05:57
seeing the same issue

**Comment by batuhangobekli** [comment] 2018-06-13 22:27
When the update will come.I will transfer if not?

**Comment by kaspermunck** [comment] 2018-06-15 12:43
The compile errors are caused by a change in Swift 4.2 described in [Abolish ImplicitlyUnwrappedOptional type](https://github.com/apple/swift-evolution/blob/master/proposals/0054-abolish-iuo.md) Swift Evolution. 

I have [forked](https://github.com/kaspermunck/ObjectMapper/commits/master) the repo and fixed the compile errors, but I don't think it should be merged into master yet. @tristanhimmelman would you accept a PR into master, or could you perhaps create a swift4.2 branch that we can submit PR's against?

**Comment by gcharita** [comment] 2018-06-15 13:17
There are already three PRs pending for this issue (#976, #978, #980), one of which have passed all tests.

**Comment by kaspermunck** [comment] 2018-06-15 13:45
Saw that moments after posting my comment. Great to have options to choose from ;-)

**Comment by gcharita** [comment] 2018-06-26 08:10
#980 solved

**Closed** 2018-06-26 15:10 UTC
