### ISSUE TITLE
Support for nil values in array of optionals (ex. [String?])

### ISSUE THREAD

**Issue by zellb** [Hearst-DD/ObjectMapper#368] opened 2016-01-13 17:51 UTC
Currently if I try to map a JSON in array of optionals the object is always empty, even if JSON array does not return any null field. Example : on my mappable struct I declare a field as follow :

 `var strings : [String?]?`

This object is always nil for all json cases below

`{"strings":["someString",null]}`
`{"strings":["someString"]}`
`{"strings":[]}`
 
Is there a way to map array of optionals to objects ?

**Comment by tristanhimmelman** [comment] 2016-01-14 13:31
Unfortunately, at the moment ObjectMapper doesn't support mapping arrays of Optionals the way you are describing.

**Comment by PhilCai1993** [comment] 2016-02-25 06:26
I think this kind of JSON is a little weird...

**Comment by lgrzywac** [comment] 2016-02-25 07:56
I have to handle similar json arrays in my app. For an array of Ints = [null, 5, null, 10] index of an element does matter - I must get value '10' using array[3] instead of array[1]

**Comment by KevM** [comment] 2016-05-14 04:38
Duplicate of #263 which has a workaround.

**Comment by tristanhimmelman** [comment] 2016-08-06 15:47
Thanks @KevM, closing this.

**Closed by tristanhimmelman** 2016-08-06 15:47 UTC
Labels: enhancement
