### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by rbukovansky** [Hearst-DD/ObjectMapper#643] opened 2016-10-24 15:47 UTC
Hi,
I'm trying to get your library compiled on Linux (Ubuntu 16.10 with Swift 3.0 RELEASE), but it is failing. See attached `build.log.txt`. Could you please take a look?

I have resolved issues with folder structure of package and on-Linux-non-existing `Cocoa` library (file: `HexColorTransform.swift`), but this is something you should probably take a look. Please, do so. Thank you.

[build.log.txt](https://github.com/Hearst-DD/ObjectMapper/files/548294/build.log.txt)

**Comment by devxoul** [comment] 2016-10-24 20:01
@rbukovansky, it seems that you're trying to build Swift 2 version of ObjectMapper (1.x). Try with [latest version](https://github.com/Hearst-DD/ObjectMapper/releases/latest).

**Comment by rbukovansky** [comment] 2016-10-25 10:20
@devxoul Could you please repost your reply? It disappeared from here. Thanks.

**Comment by devxoul** [comment] 2016-10-25 11:24
@rbukovansky It was wrong comment 😅

**Comment by wassimseif** [comment] 2016-12-19 06:24
I think the problem is that ObjectMapper uses Cocoa  which is not open source and it's not available on linux

**Comment by rbukovansky** [comment] 2016-12-19 09:05
@wassimseif As I was mentioning, I had resolved issues with Cocoa, but those in build log doesn't seem to be related to Cocoa framework.

**Comment by pournam** [comment] 2017-01-20 00:48
Hello, is there any update on this? I'm having the same exact errors, it would be ideal to have this swift JSON mapper available where JSON is used the most, server side. 
Thanks!

**Comment by foldericon** [comment] 2017-02-16 08:30
I still have issues on Linux with newest 2.2.3
```
/root/Projects/Server/Packages/ObjectMapper-2.2.3/Sources/TransformOperators.swift:251:47: error: cannot convert value of type '[String : AnyObject]' to type 'AnyObject?' in coercion
                let value = fromJSONDictionaryWithTransform(object as AnyObject?, transform: transform) ?? left
                                                            ^~~~~~
/root/Projects/Server/Packages/ObjectMapper-2.2.3/Sources/TransformOperators.swift:271:47: error: cannot convert value of type '[String : AnyObject]' to type 'AnyObject?' in coercion
                let value = fromJSONDictionaryWithTransform(object as AnyObject?, transform: transform) ?? left
                                                            ^~~~~~
/root/Projects/Server/Packages/ObjectMapper-2.2.3/Sources/TransformOperators.swift:291:63: error: cannot convert value of type '[String : AnyObject]' to type 'AnyObject?' in coercion
                let transformedDictionary = fromJSONDictionaryWithTransform(dictionary as AnyObject?, transform: transform) ?? left
                                                                            ^~~~~~~~~~
/root/Projects/Server/Packages/ObjectMapper-2.2.3/Sources/TransformOperators.swift:455:31: error: cannot convert value of type 'Array<AnyObject>' to type 'AnyObject?' in coercion
                        fromJSONArrayWithTransform(values as AnyObject?, transform: transform)
                                                   ^~~~~~
/root/Projects/Server/Packages/ObjectMapper-2.2.3/Sources/TransformOperators.swift:479:31: error: cannot convert value of type 'Array<AnyObject>' to type 'AnyObject?' in coercion
                        fromJSONArrayWithTransform(values as AnyObject?, transform: transform)
                                                   ^~~~~~
/root/Projects/Server/Packages/ObjectMapper-2.2.3/Sources/TransformOperators.swift:503:31: error: cannot convert value of type 'Array<AnyObject>' to type 'AnyObject?' in coercion
                        fromJSONArrayWithTransform(values as AnyObject?, transform: transform)
                                                   ^~~~~~
/root/Projects/Server/Packages/ObjectMapper-2.2.3/Sources/NSDecimalNumberTransform.swift:42:20: error: argument labels '(value:)' do not match any available overloads
            return NSDecimalNumber(value: double)
                   ^              ~~~~~~~~~~~~~~~
/root/Projects/Server/Packages/ObjectMapper-2.2.3/Sources/NSDecimalNumberTransform.swift:42:20: note: overloads for 'NSDecimalNumber' exist with these partially matching parameter lists: (decimal: Decimal), (string: String?), (coder: NSCoder), (floatLiteral: Double), (booleanLiteral: Bool), (integerLiteral: Int)
            return NSDecimalNumber(value: double)
```

swift --version is
```
Swift version 3.0.2 (swift-3.0.2-RELEASE)
Target: x86_64-unknown-linux-gnu
```

**Comment by tristanhimmelman** [comment] 2017-02-23 01:49
@foldericon I just pushed some changes to master. Let me know if you still have these build issues

**Comment by foldericon** [comment] 2017-02-23 10:03
@tristanhimmelman I created a pull request in case you didn't notice. It is not needed to use Any throughout, only for fromJSONArrayWithTransform and fromJSONDictionaryWithTransform.
Also NSDecimalNumber does not have the (value:) initialiser on Linux. It needs to be changed to (floatLiteral:) which works fine on all platforms.

**Comment by tristanhimmelman** [comment] 2017-02-23 15:01
The linux PR has now been merged into master. I will close this for now, however if anybody has issues, please comment and we can reopen. Thanks

**Closed by tristanhimmelman** 2017-02-23 15:01 UTC

**Comment by rbukovansky** [comment] 2017-02-24 08:22
Yup, `build` is fine now, thanks @foldericon, but is there a plan to have full `test` suite for Linux as well?

**Comment by tristanhimmelman** [comment] 2017-02-24 15:54
I think including Linux in the Travis CI test suite sounds like a great idea. I personally do not have the bandwidth to take this on at the moment, but would be really happy for someone else to do so :).
