### ISSUE TITLE
console printing for nill value toJSONString

### ISSUE THREAD

**Issue by gauravds** [Hearst-DD/ObjectMapper#647] opened 2016-10-25 11:08 UTC
Most common user case of model mapper is make BaseModel (For ObjC support inherit from NSObject) and other all model inherits from this. To log on console override the description like [JSONModel](https://github.com/jsonmodel/jsonmodel). 

```
open class BaseModel: NSObject, Mappable  {

    required public override init() {
        super.init()
    }

    required public init?(map: Map) {}

    // FIXME: prints only available object, removed nil object; PRINT ALL
    override open var description: String {
        return self.toJSONString(prettyPrint: true) ?? "<NO description available for \(type(of: self)).>"
    }

    public func mapping(map: Map) {}

}
```

All model must inherit from BaseModel like User

```
open class User: BaseModel {

    open var title: String? = "Mr"
    open var firstName: String?
    open var lastName: String?

    override open func mapping(map: Map) {
        title <- map["title"]
        firstName <- map["first_name"]
        lastName <- map["last_name"]
     }
}
```

Now here is the problem if raw JSON has `last_name` nil and trying to print user model, it will print only title & firstName, lastName field is eliminated from `toJSONString` method. 
While we all expect that lastName field must exist and field value may be null. 

It's not an issue, it's a feature which should on ModelMapper. [Here we can solve it may be.](https://github.com/Hearst-DD/ObjectMapper/blob/master/Sources/ToJSON.swift#L68-L94). 

Also another suggestion is modify the prettyJSON default as true
`func toJSONString(prettyPrint: Bool = false) -> String?` to `func toJSONString(prettyPrint: Bool = true) -> String?`

**Comment by tristanhimmelman** [comment] 2016-11-21 17:26
Closing this as it is a duplicate of #177

**Closed by tristanhimmelman** 2016-11-21 17:26 UTC
